language: node_js
env: IN_TRAVIS=true
node_js:
- '0.10'
notifications:
  email:
    recipients:
    - dev@metron.incubator.apache.org
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure: ftMVn8V34kdqbwVUDMoKgbEKG4KzywcAIxByW0bUes18Fl4e0Tc5wUajfKCtB3ih9fazNgClQgoDZWhYGZ/Ik7o/DxwJdMd7SN36Vfl412LQiV7IVPO+vvVVvrAH5RxXA1yxQveNlF7DI6ANRwVISs/OsAplznIzmyqsJ/onn1I=

addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database metron_test;' -U postgres
  - script/migrate up -e ci
